
# 路径配置
paths:
  #日志地址
  log_path : /mnt/nfs/Config/Log/Plane

# 链接配置
links:
  # 没有自己logo的图床链接的话就先用默认的
  logo_mesl : https://lsky.pantheon.center/image/2023/04/02/642940f3a50c1.png
  # 要爬取的机场链接地址
  head_bark : https://bark.pantheon.center/WSeN8LCGbCDZqHAJMTmeHP

#账号密码
account:
  email: 1661862073@qq.com
  password: 022760Mesl